Added prop blockDocument to block field in user profile page
vtex-apps/my-account pull request #202
Opened 2021-02-10 18:31 UTC by jailsondamasceno

#### What did you change? \*

A property has been added to the module called blockDocument

#### Why? \*
The customer needed to block the document field (cpf). Once added, the user should no longer edit. The customer wanted unique accounts per user.

#### How to test it? \*

1. Pass the blockDocument property in the declaration of the my-account app in the store

2. Link the vtex.profile-forme app on the tksio-549 branch in the my-account module. It is a dependency.

3. Link the three store / my-account / profile-form repositories and change the property value in the store. By default the speaker is underfid.
If you do not pass the property or pass the false value, the field allows changes.
If it is set to true and the field still has no saved value, the field will also allow editing, if the field is already saved, the field is blocked.

https://profileform--tokstokio.myvtex.com/account/#/profile/edit

#### prop
![image](https://user-images.githubusercontent.com/78736383/107518517-dbf8ab80-6b8d-11eb-932e-cce56e472d34.png)

#### Before
![bofore](https://user-images.githubusercontent.com/78736383/107516673-83c0aa00-6b8b-11eb-9746-b56e0bcebc44.PNG)

#### After
![affter](https://user-images.githubusercontent.com/78736383/107516749-9aff9780-6b8b-11eb-9596-ab27c35b70d6.PNG)

#### Related to / Depends on?

https://listastokstok.atlassian.net/browse/TKSIO-549

#### Types of changes \*

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical improvements

2021-02-11 11:49 UTC, jailsondamasceno commented
The files that are giving error in the Lint check have not been changed in this feature, they are already like this. There's something with the addresses. I just messed with my account

2021-03-15 13:40 UTC, salesfelipe requested changes

2021-03-15 13:40 UTC, salesfelipe commented on react/components/pages/ProfileEdit.tsx
> +  }),
No need for this change

2021-03-15 13:40 UTC, salesfelipe commented on react/index.tsx
> +  }
No need for this change

2021-03-15 13:40 UTC, salesfelipe commented on react/index.tsx
> +interface MyAccountProps {
```suggestion
interface Props {
```

2021-03-15 13:40 UTC, salesfelipe commented on react/index.tsx
> +class MyAccount extends Component<MyAccountProps> {
```suggestion
class MyAccount extends Component<Props> {
```

2021-03-15 13:40 UTC, salesfelipe commented on react/components/Profile/ProfileFormBox.tsx
> +  profile: Profile,
```suggestion
  profile: Profile
```

2021-03-15 13:40 UTC, salesfelipe commented on react/components/AppRouter.tsx
> +interface AppRouterProps {
```suggestion
interface Props {
```

2021-03-15 13:40 UTC, salesfelipe commented on react/components/AppRouter.tsx
> +  }
```suggestion
```

2021-03-15 13:40 UTC, salesfelipe commented on react/components/AppRouter.tsx
> +class AppRouter extends Component<AppRouterProps> {
```suggestion
class AppRouter extends Component<Props> {
```

2021-03-15 13:40 UTC, salesfelipe commented on docs/README.md
> +| `blockDocument` | `boolean` | Enables or disables editing the document field in my account  | `underfid` |
```suggestion
| `blockDocument` | `boolean` | Enables or disables editing the document field in MyAccount  | `undefined` |
```

2021-03-15 13:40 UTC, salesfelipe commented on CHANGELOG.md
> +- Added prop `blockDocument` to Enables or disables editing the document field in my account
Hi, first of all, thank you for your contribution. Just a couple of changes.
```suggestion
- Prop `blockDocument` to Enables or disables editing the document field in MyAccount
```

2021-03-15 14:57 UTC, jailsondamasceno commented on CHANGELOG.md
> +- Added prop `blockDocument` to Enables or disables editing the document field in my account
@salesfelipe  Hey, how's it going? I made all the suggested adjustments! I'm available.

2021-03-15 15:01 UTC, salesfelipe commented on CHANGELOG.md
> +- Added prop `blockDocument` to Enables or disables editing the document field in my account
Good, what about yourself? I think you forgot to push the changes... Also, there is a conflict on the changelog

2021-03-15 15:10 UTC, jailsondamasceno commented on CHANGELOG.md
> +- Added prop `blockDocument` to Enables or disables editing the document field in my account
I had commented before the push. Which branch should I update with, the master?

2021-03-15 17:33 UTC, jailsondamasceno commented
@salesfelipe They have been corrected.

2021-03-15 17:34 UTC, jailsondamasceno commented on CHANGELOG.md
> +- Added prop `blockDocument` to Enables or disables editing the document field in my account
resolved

2021-03-17 18:36 UTC, salesfelipe approved these changes

2021-03-17 18:36 UTC, merged

2021-03-17 18:37 UTC, salesfelipe commented
@jailsondamasceno Thanks again for your contribution 🙏 🥳 🚀